### PR TITLE
fix: separate known-peers index from peer store to fix blocking for shared URLs

### LINKED ISSUE #450: Problems and limitations in the current blocking implementation
The current implementation of blocking (as of commit e9c75f2d2356fac02959db2295a20f820c702aef) contains an inherent contradiction in that the implementation on the one hand assumes that the peer store is kept clean of blocked agents so as to not initiate gossip with them (or return them as available peers via helper functions like [get_responsive_remote_agents_near_location](https://github.com/holochain/kitsune2/blob/e9c75f2d2356fac02959db2295a20f820c702aef/crates/core/src/common.rs#L86) used by the kitsune host), while at the same time assuming that agent infos in the peer store can be used to associate peer urls to agent ids of potentially blocked agents. However, if agent infos of blocked agents are not supposed to be in the peer store in the first place (i.e. [not getting inserted](https://github.com/holochain/kitsune2/blob/e72edc14fa2017f9ab9f5608d5562a0ede4580e3/crates/api/src/peer_store.rs#L10-L12) as well as [getting removed when blocked](https://github.com/holochain/kitsune2/blob/e72edc14fa2017f9ab9f5608d5562a0ede4580e3/crates/api/src/blocks.rs#L29-L30)), then the peer store can't actually meaningfully be used to [associate peer urls to agent agent infos](https://github.com/holochain/kitsune2/blob/e72edc14fa2017f9ab9f5608d5562a0ede4580e3/crates/core/src/factories/core_access.rs#L61-L62) and then check [whether the agents of the associated agent infos are blocked](https://github.com/holochain/kitsune2/blob/e72edc14fa2017f9ab9f5608d5562a0ede4580e3/crates/core/src/factories/core_access.rs#L86), because the blocked agents won't ever be returned from the peer store in the first place.

The reason this issue didn't show up in tests is that the access decision [gets removed if no agent for a peer url is found in the peer store](https://github.com/holochain/kitsune2/blob/e72edc14fa2017f9ab9f5608d5562a0ede4580e3/crates/core/src/factories/core_access.rs#L77-L84). And this happens as part of calling `block()` on the `Blocks` module which [removes the agent from the peer store](https://github.com/holochain/kitsune2/blob/e72edc14fa2017f9ab9f5608d5562a0ede4580e3/crates/kitsune2/tests/blocks.rs#L466-L467), thereby invoking the peer update listener that has been registered by the `CoreAccessState`. And if no access decision is found for a peer url, [it is considered blocked](https://github.com/holochain/kitsune2/blob/e72edc14fa2017f9ab9f5608d5562a0ede4580e3/crates/core/src/factories/core_space.rs#L277). But this will only work if there is only a single blocked agent trying to connect on a given peer url and zero non-blocked ones. Otherwise [the list of agents won't be empty here](https://github.com/holochain/kitsune2/blob/e72edc14fa2017f9ab9f5608d5562a0ede4580e3/crates/core/src/factories/core_access.rs#L77-L84) in the peer update listener and we won't find a blocked peer in the peer store because the one that is blocked has deliberately not been inserted into the peer store.

This means that we are currently still effectively implementing "only if *all* agents associated with a peer url are blocked, messages from that peer  url get blocked" rather than "if *any* agent associated with a peer url is blocked, messages from that peer url get blocked", as can for example be (and has been) verified by modifying [this blocks test](https://github.com/holochain/kitsune2/blob/e9c75f2d2356fac02959db2295a20f820c702aef/crates/kitsune2/tests/blocks.rs#L920) by adding an additional local agent to Alice's conductor on [this line](https://github.com/holochain/kitsune2/blob/e9c75f2d2356fac02959db2295a20f820c702aef/crates/kitsune2/tests/blocks.rs#L943) alongside the agent that will [get blocked](https://github.com/holochain/kitsune2/blob/e9c75f2d2356fac02959db2295a20f820c702aef/crates/kitsune2/tests/blocks.rs#L991).

Associated [MM thread](https://chat.holochain.org/holo/pl/q633w6ifapdy7npo5qqd5ns8ia).

And a hackmd providing more context about the broader problem space: https://hackmd.io/RpkAEte7TVOsM6cyjDhf-A

### PR DESCRIPTION
**Pull request by synchwire**
Closes #450

## Problem

The blocking implementation had a fundamental design contradiction:

- Blocked agents are excluded from the `PeerStore` (not inserted; removed on block) to prevent gossip with them
- `CorePeerAccessState` used `PeerStore::get_by_url` to map peer URLs → agent IDs in order to decide whether to block incoming connections

These assumptions are mutually incompatible. When a blocked agent is removed from the peer store, the URL lookup can no longer find them. If a non-blocked agent shares the same peer URL, the lookup finds the non-blocked agent, sees no block, and incorrectly grants access — allowing the blocked agent's traffic through.

**Net result:** blocking only worked when *all* agents at a peer URL were blocked, not when *any* were.

## Solution

Introduce a new `KnownPeers` trait in the `api` crate: an append-only index of all ever-seen agent infos, including blocked ones, used purely for URL → agent ID resolution by the access control layer.

- `KnownPeers::record` — records agent infos without any block filtering
- `KnownPeers::get_by_url` — returns all known agents at a URL regardless of block status

`CorePeerAccessState` now uses `DynKnownPeers` for URL lookups instead of `DynPeerStore`. Agent infos are recorded into `KnownPeers` before the block filter runs, so blocked agents remain findable for access control purposes even after being removed from the peer store.

A new integration test verifies the fixed behaviour: a blocked agent sharing a peer URL with a non-blocked agent is correctly blocked.

## Release Notes

* **New Features**
  * Added a known-peers index for independent URL-to-agent-ID resolution that persists even when peers are blocked or filtered from the peer store, enabling more robust peer discovery and access control decisions.

### CODE REVIEW

File: crates/api/src/known_peers.rs [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+        &self,
+        agent_infos: Vec<Arc<AgentInfoSigned>>,
+    ) -> BoxFut<'_, K2Result<()>>;
+
+    /// Look up all known agents reachable at the given URL, regardless of
+    /// their current block status.
+    fn get_by_url(
+        &self,
+        url: Url,
+    ) -> BoxFut<'_, K2Result<Vec<Arc<AgentInfoSigned>>>>;
```
Comment (ThetaSinner) [inline crates/api/src/known_peers.rs]: Do we need to have stored the entire `AgentInfoSigned`? They're small but not that small.

File: crates/api/src/peer_store.rs [hunk 2]
```diff
@@ -86,6 +86,7 @@ pub trait PeerStoreFactory: 'static + Send + Sync + std::fmt::Debug {
         builder: Arc<Builder>,
         space_id: SpaceId,
         blocks: DynBlocks,
+        known_peers: DynKnownPeers,
```
Comment (ThetaSinner) [inline crates/api/src/peer_store.rs:95]: The expectations for peer store implementations should be documented. Where we have integrations between modules, we surface them in documentation to make it easier to implement replacement modules as required.

File: crates/core/src/factories/core_bootstrap/test.rs [hunk 3]
```diff
@@ -96,9 +96,15 @@ impl Test {
...
+            .create(builder.clone(), S1.clone())
+            .await
+            .unwrap();
+
         let peer_store = builder
             .peer_store
-            .create(builder.clone(), S1.clone(), blocks)
+            .create(builder.clone(), S1.clone(), blocks, known_peers)
             .await
             .unwrap();
```
Comment (ThetaSinner) [inline crates/core/src/factories/core_bootstrap/test.rs:109]: Should the space hold a reference to this new module too? For functional testing, I'd expect to be able to retrieve a handle to this module.

File: crates/core/src/factories/core_access.rs [hunk 4]
```diff
@@ -167,3 +175,126 @@ impl PeerAccessState for CorePeerAccessState {
...
+            known_peers,
+        ))
+    }
+
+    /// Regression test: blocking one agent at a URL must block the URL even
+    /// when a non-blocked agent also resides at that URL.
+    ///
+    /// Before the `KnownPeers` fix the blocked agent was removed from the
+    /// `PeerStore`, so `get_by_url` only saw the non-blocked agent and
+    /// returned `Granted` instead of `Blocked`.
```
Comment (ThetaSinner) [inline crates/core/src/factories/core_access.rs]: Don't document past states, focus on what the current state of the code is and why.

File: crates/core/src/factories/core_access.rs [hunk 5]
```diff
@@ -167,3 +175,126 @@ impl PeerAccessState for CorePeerAccessState {
...
+        // at the same URL, the URL must be Blocked.
+        let decision = access_state.get_access_decision(url.clone()).unwrap();
+        assert_eq!(
+            decision.map(|d| d.decision),
+            Some(AccessDecision::Blocked),
+            "expected Blocked after agent_1 at the shared URL was blocked"
+        );
+    }
+
+    /// Sanity test: a URL with only non-blocked agents remains Granted.
```
Comment (ThetaSinner) [inline crates/core/src/factories/core_access.rs]: Confusing wording, this is just a happy path case. Skip the "sanity" wording and also "stays". Just "is".

File: crates/core/src/factories/mem_known_peers.rs [hunk 6]
```diff
@@ -0,0 +1,101 @@
...
+use tokio::sync::Mutex;
+
+/// A production-ready memory-based known-peers factory.
+///
+/// This stores agent infos in an in-memory hash map by [`AgentId`], indexed
+/// by [`Url`].  Entries are never removed – the whole point of this store is
+/// to retain the URL → agent mapping even after an agent has been blocked and
+/// removed from the [`crate::factories::MemPeerStoreFactory`].
+#[derive(Debug)]
+pub struct MemKnownPeersFactory {}
```
Comment (ThetaSinner) [inline crates/core/src/factories/mem_known_peers.rs]: If it's a production one, we should name it `CoreKnownPeersFactory` and not `Mem` prefix. We haven't been consistent about this but that's the intended naming pattern.

File: crates/api/src/known_peers.rs (hunk 1 above)
Comment (synchwire) [reply crates/api/src/known_peers.rs]: Changed. `get_by_url` now returns `Vec<AgentId>` and the internal storage keeps only `AgentId → Option<Url>` pairs instead of full `AgentInfoSigned` structs.

File: crates/api/src/peer_store.rs (hunk 2 above)
Comment (synchwire) [reply crates/api/src/peer_store.rs:95]: Added documentation on `PeerStoreFactory::create` explaining that implementations must call `KnownPeers::record` with every batch of agent infos before applying block or expiry filtering.

File: crates/core/src/factories/core_bootstrap/test.rs (hunk 3 above)
Comment (synchwire) [reply crates/core/src/factories/core_bootstrap/test.rs:109]: Added `fn known_peers(&self) -> &DynKnownPeers` to the `Space` trait. `CoreSpace` now stores and exposes the reference.

File: crates/core/src/factories/core_access.rs (hunk 4 above)
Comment (synchwire) [reply crates/core/src/factories/core_access.rs]: Removed. The test doc now just states the invariant being tested.

File: crates/core/src/factories/core_access.rs (hunk 5 above)
Comment (synchwire) [reply crates/core/src/factories/core_access.rs]: Fixed. Now reads: "A URL with only non-blocked agents is Granted."

File: crates/core/src/factories/mem_known_peers.rs (hunk 6 above)
Comment (synchwire) [reply crates/core/src/factories/mem_known_peers.rs]: Renamed to `CoreKnownPeersFactory` / `CoreKnownPeers` and moved the file to `core_known_peers.rs`. Updated all references across the codebase.

**Review by jost-s — APPROVED** [review]
Looks great!

A concern is that this is an in-memory store that only grows while kitsune is running. We might have to solve that if it becomes an issue.
