### PR TITLE
Initiate faster after failure

### LINKED ISSUE #177: Retrigger gossip initiation if it fails
If we fail to initiate then we shouldn't wait the full initiation interval to try again, we should retry as soon as we discover the failure.

### PR DESCRIPTION
**Pull request by ThetaSinner**
Closes #177

This PR has created some flaky tests. The cause will be resolved by #182, so that should be merged before this one

### CODE REVIEW

File: crates/core/src/factories/core_fetch.rs [hunk 1]
```diff
@@ -240,7 +241,7 @@ impl CoreFetch {
                     outgoing_request_tx.clone(),
                     outgoing_request_rx.clone(),
                     space_id.clone(),
-                    transport.clone(),
+                    Arc::downgrade(&transport),
```
Comment (ThetaSinner) [inline crates/core/src/factories/core_fetch.rs:244]: To test this change, I needed offline agents. The simplest way to do that was to start a test harness and shut it down. At that point, I discovered we can't shut down K2 properly. I don't know if I caught everything but this was the common issue that prevented gossip from shutting down at least.

The modules I've made this change to register themselves as module handlers, so the transport has a reference to us. We can't then have an owned reference to the transport and expect everything to drop correctly.

File: crates/core/src/factories/core_space.rs [hunk 2]
```diff
@@ -214,6 +214,8 @@ struct CoreSpace {
 
 impl Drop for CoreSpace {
     fn drop(&mut self) {
+        tracing::trace!("Dropping core space");
```
Comment (ThetaSinner) [inline crates/core/src/factories/core_space.rs:217]: This was helpful for debugging, I'd like to keep this at `trace` level but I don't have to

File: crates/gossip/src/gossip.rs [hunk 3]
```diff
@@ -118,11 +115,10 @@ pub(crate) struct K2Gossip {
...
     pub(crate) agent_verifier: DynVerifier,
-    pub(crate) response_tx: Sender<GossipResponse>,
-    pub(crate) _response_task: Arc<DropAbortHandle>,
-    pub(crate) _initiate_task: Arc<Option<DropAbortHandle>>,
-    pub(crate) _timeout_task: Arc<Option<DropAbortHandle>>,
-    pub(crate) _dht_update_task: Arc<Option<DropAbortHandle>>,
+    pub(crate) transport: Weak<dyn Transport>,
+    pub(crate) _initiate_task: Arc<std::sync::Mutex<Option<DropAbortHandle>>>,
+    pub(crate) _timeout_task: Arc<std::sync::Mutex<Option<DropAbortHandle>>>,
+    pub(crate) _dht_update_task: Arc<std::sync::Mutex<Option<DropAbortHandle>>>,
```
[the remark this answers is not in the document]
Comment (ThetaSinner) [reply crates/gossip/src/gossip.rs:121]: I could probably use a RefCell but I don't think it's that important here

File: crates/gossip/src/respond/accept.rs [hunk 4]
```diff
@@ -25,13 +25,6 @@ impl K2Gossip {
         let (mut lock, initiated) =
             self.check_accept_state(&from_peer, &accept).await?;
 
-        // Only once the other peer has accepted should we record that we've tried to
-        // gossip with them. Otherwise, we risk lock each other out if we both record
-        // a last gossip timestamp and try to initiate at the same time.
-        self.peer_meta_store
```
Comment (ThetaSinner) [inline crates/gossip/src/respond/accept.rs:31]: Moved, see above

File: crates/gossip/src/respond/harness.rs [hunk 5]
```diff
@@ -38,19 +39,20 @@ impl RespondTestHarness {
...
-        impl TxHandler for NoopHandler {}
-
-        let transport = builder
-            .transport
-            .create(builder.clone(), Arc::new(NoopHandler))
-            .await
-            .unwrap();
-
-        let (tx, rx) = tokio::sync::mpsc::channel(1);
+        let (tx, rx) = tokio::sync::mpsc::channel(100);
```
Comment (ThetaSinner) [inline crates/gossip/src/respond/harness.rs:42]: Now that the way the gossip module handles sending messages has changed, we're forced to mock the transport to be able to receive outgoing messages and check them in tests.

Well, we could use the transport, but we're forced to do something other than read the outgoing messages directly from the gossip module.

File: crates/gossip/src/timeout.rs [hunk 6]
```diff
@@ -59,6 +69,14 @@ async fn remove_timed_out_rounds(
                     );
                 }
 
+                // If we failed to initiate, then we want to try again. Otherwise, an unavailable
+                // peer can prevent us from initiating gossip.
+                if matches!(state.stage, RoundStage::Initiated(_)) {
```
Comment (ThetaSinner) [inline crates/gossip/src/timeout.rs:74]: On a timeout in the initiate stage, trigger initiate to run again. I think that's the only time we should do it on a timeout.

File: crates/gossip/src/gossip.rs [hunk 7]
```diff
@@ -279,11 +253,20 @@ impl K2Gossip {
             target_peer_url,
         );
 
-        send_gossip_message(
-            &self.response_tx,
-            target_peer_url,
+        // Record that we're initiating gossip with this peer.
```
[the remark this answers is not in the document]
Comment (ThetaSinner) [reply crates/gossip/src/gossip.rs:256]: https://github.com/holochain/kitsune2/issues/181

File: crates/core/src/factories/core_fetch.rs [hunk 8]
```diff
@@ -295,12 +296,19 @@ impl CoreFetch {
         outgoing_request_tx: Sender<OutgoingRequest>,
         outgoing_request_rx: Arc<tokio::sync::Mutex<Receiver<OutgoingRequest>>>,
         space_id: SpaceId,
-        transport: DynTransport,
+        transport: Weak<dyn Transport>,
```
Comment (neonphog) [inline crates/core/src/factories/core_fetch.rs:299]: This feels like it may be a pretty common pattern. Do you think we should create an official `pub type WeakTransport = Weak<dyn Transport>;` in the api crate?

File: crates/core/src/factories/core_fetch.rs [hunk 9]
```diff
@@ -295,12 +296,19 @@ impl CoreFetch {
...
         re_insert_outgoing_request_delay: u32,
     ) {
         while let Some((op_id, peer_url)) =
             outgoing_request_rx.lock().await.recv().await
         {
+            let Some(transport) = transport.upgrade() else {
```
Comment (neonphog) [inline crates/core/src/factories/core_fetch.rs:305]: wuuuuuut is this syntax ?!?/*&#* :exploding_head:

File: crates/core/src/factories/core_space.rs (hunk 2 above)
Comment (neonphog) [reply crates/core/src/factories/core_space.rs:217]: Seems like tracing to me :+1:

File: crates/gossip/src/gossip.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (neonphog) [reply crates/gossip/src/gossip.rs:121]: RefCell isn't sync. But you could use [OnceLock](https://doc.rust-lang.org/std/sync/struct.OnceLock.html)s. But this is also fine.

**Review by neonphog — DISMISSED** [review]
Nice, looks good to me :+1:

File: crates/gossip/src/gossip.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (ThetaSinner) [reply crates/gossip/src/gossip.rs]: OnceLock would better express what this is doing, switched https://github.com/holochain/kitsune2/pull/180/commits/7d7f9b31be600c854209937010b3e71aecc2d7ed

File: crates/core/src/factories/core_fetch.rs (hunk 9 above)
Comment (ThetaSinner) [reply crates/core/src/factories/core_fetch.rs:305]: Cool right :) It lets you flatten out the let/if/let/else/return that is so often a useful pattern but ends up with nested code. I saw it in a diff on some other project when trying to track down a bug and decided it was worth remembering :D

File: crates/gossip/src/initiate.rs [hunk 10]
```diff
@@ -58,14 +75,18 @@ pub fn spawn_initiate_task(
...
+                            rush_to_first_initiated_round = false;
                             tracing::info!("Initiated gossip with {}", url);
                         }
                         Ok(false) => {
                             // Don't log here, will already have logged the reason
                         }
                         Err(e) => {
                             tracing::error!("Error initiating gossip: {:?}", e);
+
+                            if let Err(err) = here_force_initiate.try_send(()) {
```
[the remark this answers is not in the document]
Comment (ThetaSinner) [reply crates/gossip/src/initiate.rs:87]: Actually, this is not so serious. We should only stay in this loop as long as there are peers we haven't attempted to gossip with recently. So it could be noisy if something is broken but it shouldn't spin endlessly.

File: crates/core/src/factories/core_fetch.rs (hunk 8 above)
Comment (ThetaSinner) [reply crates/core/src/factories/core_fetch.rs]: Yes, that's a good idea. That gives me a place to write about this in the code for people to find

https://github.com/holochain/kitsune2/pull/180/commits/5996eca03de6b117bc6a3123c269b08bb8ae4423
https://github.com/holochain/kitsune2/pull/180/commits/27adb70458409647d72a28478b67eb7ddc30882c
https://github.com/holochain/kitsune2/pull/180/commits/77ec3588227677845cfa3f6d2c96dcae3c50048f

Comment (neonphog) [reply crates/core/src/factories/core_fetch.rs]: woot :+1:

**Review by neonphog — APPROVED** [review]

File: crates/gossip/src/gossip.rs [hunk 11]
```diff
@@ -1009,4 +1018,103 @@ mod test {
...
+                    .await
+                    .unwrap()
+                    .is_some();
+            }
+
+            if all_tried {
+                break;
+            }
+
+            tokio::time::sleep(std::time::Duration::from_millis(10)).await;
```
Comment (jost-s) [inline crates/gossip/src/gossip.rs:1099]: The sleep is included in the macro.
```suggestion
```

File: crates/gossip/src/gossip.rs [hunk 12]
```diff
@@ -1009,4 +1018,103 @@ mod test {
...
+                .peer_meta_store
+                .last_gossip_timestamp(good_agent_url.clone())
+                .await
+                .unwrap()
+                .is_some()
+            {
+                break;
+            }
+
+            tokio::time::sleep(std::time::Duration::from_millis(10)).await;
```
Comment (jost-s) [inline crates/gossip/src/gossip.rs:1114]:
```suggestion
```

File: crates/gossip/src/harness.rs [hunk 13]
```diff
@@ -264,6 +264,56 @@ impl K2GossipFunctionalTestHarness {
...
+                    };
+
+                    if agent.storage_arc == arc {
+                        break;
+                    }
+
+                    tokio::time::sleep(std::time::Duration::from_millis(5)).await;
+                }
+            }
+        }).await.expect("Timed out waiting for agent to be in peer store with the requested arc");
```
Comment (jost-s) [inline crates/gossip/src/harness.rs:307]: Use the `iter_check` here too?
